server:
  port: 8080

spring:
  datasource:
    username: postgres
    password: 355037
    url: jdbc:postgresql://localhost:5432/searchengine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    #context
    #parameters
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
